name: test-wsc-seurat-3
dependencies:
  - bats
  - r-optparse
  - libpng
  - r-cairo
  - r-seurat<=3.1.5
  - r-loom
  - r-spatstat<=1.64_1
  - r-spatstat.data<=1.64_1
  - r-spatstat.utils<=1.64_1
  - libopenblas
  - bioconductor-scater
