name: test-wsc-seurat-3
dependencies:
  - bats
  - r-optparse
  - r-seurat<4.0.0
  - r-loom
  - r-base >=4.0
  - r-matrix <=1.3_2
  - r-spatstat <=1.64_1
  - r-spatstat.data <=1.64_1
  - r-spatstat.utils <=1.64_1
  - bioconductor-scater
