name: test-wsc-seurat-3
dependencies:
  - bats
  - r-optparse
  # - libpng
  # - r-cairo
  - r-seurat<4.0.0
  - r-loom
  - defaults::r-base<=3.6.1
  - r-spatstat<=1.64_1
  - r-spatstat.data<=1.64_1
  - r-spatstat.utils<=1.64_1
  # - libopenblas
  - bioconductor-scater
