name: test-wsc-seurat-4
dependencies:
  - bats
  - r-optparse
  - r-remotes
  - libpng
  - r-cairo
  - r-seurat=4.0.0
  - r-loom
  - hdf5-external-filter-plugins
  - bioconductor-scater
  - r-seuratdisk
